# Generated by Django 3.1.3 on 2020-11-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Паспорт номер'),
        ),
    ]
