# Generated by Django 3.1.3 on 2020-11-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='client_type',
            field=models.CharField(blank=True, choices=[(1, 'Физическое лицо'), (2, 'Юридик лицо')], default=(2, 'Юридик лицо'), max_length=100, null=True, verbose_name='Тип клиента'),
        ),
    ]
