# Generated by Django 3.0 on 2020-11-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisteredPolises',
        ),
    ]
