# Generated by Django 3.0 on 2020-11-11 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policytransfers',
            old_name='policies',
            new_name='policy',
        ),
    ]
