# Generated by Django 3.0 on 2020-11-03 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=14)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='PoliciesIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_number', models.CharField(max_length=128, unique=True, verbose_name='Номер акта')),
                ('act_date', models.DateTimeField(verbose_name='Дата акта')),
                ('policy_number_from', models.PositiveIntegerField(default=1, verbose_name='Номер полиса с')),
                ('policy_number_to', models.PositiveIntegerField(default=2, verbose_name='Номер полиса до')),
                ('is_free_policy', models.BooleanField(default=False, verbose_name='Свободный')),
                ('document', models.FileField(blank=True, default=None, null=True, upload_to='policies_income', verbose_name='Документ')),
                ('cr_on', models.DateTimeField(auto_now_add=True)),
                ('cr_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_income_cr_by', to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies_income_up_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Поступления полис',
                'verbose_name_plural': 'Поступления полисы',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_free_generated', models.BooleanField(default=False, verbose_name='Свободный')),
                ('policy_number', models.PositiveIntegerField(verbose_name='Номер')),
                ('client_type', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('date_from', models.DateField(blank=True, default=None, null=True)),
                ('date_to', models.DateField(blank=True, default=None, null=True)),
                ('goal', models.CharField(blank=True, default=None, max_length=2048, null=True)),
                ('zone', models.CharField(blank=True, default=None, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolicySeriesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, verbose_name='Код')),
                ('cr_on', models.DateTimeField(auto_now_add=True)),
                ('cr_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_series_cr_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Серии полиса',
                'verbose_name_plural': 'Серии полисов',
            },
        ),
        migrations.CreateModel(
            name='PolicyTransfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_number', models.CharField(max_length=128, verbose_name='Номер акта')),
                ('act_date', models.DateTimeField(verbose_name='Дата акта')),
                ('policy_number_from', models.PositiveIntegerField(default=1, verbose_name='Номер полиса с')),
                ('policy_number_to', models.PositiveIntegerField(default=2, verbose_name='Номер полиса до')),
                ('document', models.FileField(upload_to='registered_polis', verbose_name='Документ')),
                ('cr_on', models.DateTimeField(auto_now_add=True)),
                ('cr_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_transfers_cr_by', to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_transfers_up_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='ActFields',
            new_name='PolicyFields',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='address',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='pledger',
            name='address',
        ),
        migrations.RemoveField(
            model_name='pledger',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='pledger',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='pledger',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_bank', to='insurance.Bank'),
        ),
        migrations.AddField(
            model_name='branch',
            name='series',
            field=models.CharField(default='AAA', max_length=10, verbose_name='Серии'),
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductType',
        ),
        migrations.DeleteModel(
            name='Act',
        ),
        migrations.AddField(
            model_name='policytransfers',
            name='to_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.Branch'),
        ),
        migrations.AddField(
            model_name='policy',
            name='beneficiary',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.Beneficiary'),
        ),
        migrations.AddField(
            model_name='policy',
            name='income_session',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.PoliciesIncome', verbose_name='Policies income session'),
        ),
        migrations.AddField(
            model_name='policy',
            name='pledger',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.Pledger'),
        ),
        migrations.AddField(
            model_name='policy',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.ProductType'),
        ),
        migrations.AddField(
            model_name='policy',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.PolicySeriesType'),
        ),
        migrations.AddField(
            model_name='policiesincome',
            name='policy_series',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.PolicySeriesType', verbose_name='Серии полиса'),
        ),
    ]
