# Generated by Django 3.1.3 on 2020-11-25 04:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_auto_20201124_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='cr_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 4, 25, 59, 684645, tzinfo=utc), verbose_name='created on'),
        ),
    ]
