# Generated by Django 3.1.3 on 2020-11-22 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_auto_20201122_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='has_beneficiary',
            field=models.BooleanField(default=False, verbose_name='Has beneficiary'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='has_pledger',
            field=models.BooleanField(default=False, verbose_name='Has pledger'),
        ),
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.DateField(verbose_name='From date')),
                ('to_time', models.DateField(verbose_name='To date')),
                ('individual_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.individualclient')),
                ('legal_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.legalclient')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insurance.producttype')),
            ],
        ),
    ]
