# Generated by Django 3.1.3 on 2020-11-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_auto_20201123_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='contract_type',
            field=models.CharField(choices=[('1', 'Leasing'), ('2', 'Loan')], default=('2', 'Loan'), max_length=20),
        ),
        migrations.AlterField(
            model_name='policyfields',
            name='value',
            field=models.CharField(blank=True, default=None, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='productfield',
            name='input_type',
            field=models.CharField(choices=[('1', 'Text'), ('2', 'Number'), ('3', 'Single selection'), ('4', 'Multi selection'), ('5', 'Currency')], default=('1', 'Text'), max_length=128),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='client_type',
            field=models.CharField(blank=True, choices=[('1', 'Физическое лицо'), ('2', 'Юридик лицо')], default=('2', 'Юридик лицо'), max_length=100, null=True, verbose_name='Тип клиента'),
        ),
    ]
