# Generated by Django 3.0 on 2020-11-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_delete_registeredpolises'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InsurancePeriod',
        ),
    ]
