# Generated by Django 3.1.3 on 2020-11-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_auto_20201123_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfield',
            name='value',
            field=models.CharField(blank=True, default=None, max_length=4096, null=True),
        ),
    ]
