# Generated by Django 3.0 on 2020-11-11 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance', '0003_policyretransfer_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceoffice',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_director', to=settings.AUTH_USER_MODEL),
        ),
    ]
