# Generated by Django 3.0 on 2020-11-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_delete_insuranceperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
