# Generated by Django 3.1.3 on 2020-11-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_auto_20201122_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='contract_type',
            field=models.CharField(choices=[(2, 'Loan'), (1, 'Leasing')], default=(2, 'Loan'), max_length=20),
        ),
    ]
