# Generated by Django 3.0 on 2020-11-03 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_auto_20201103_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='insurer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='insurer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='insurer',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='insurer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='insurer',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.Human'),
        ),
    ]
