# Generated by Django 3.0 on 2020-11-03 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_auto_20201103_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='address',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='mfo',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='individualclient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='individualclient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='individualclient',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='individualclient',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='individualclient',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='pledger',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='bank',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.Human'),
        ),
        migrations.AddField(
            model_name='individualclient',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.Human'),
        ),
        migrations.AlterField(
            model_name='human',
            name='address',
            field=models.CharField(default=None, max_length=1024, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='human',
            name='first_name',
            field=models.CharField(default=None, max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='human',
            name='last_name',
            field=models.CharField(default=None, max_length=128, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='human',
            name='middle_name',
            field=models.CharField(default=None, max_length=128, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='human',
            name='phone',
            field=models.CharField(default=None, max_length=14, verbose_name='Номер телефона'),
        ),
    ]
