# Generated by Django 3.1.3 on 2020-11-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_applicationform_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfield',
            name='input_type',
            field=models.CharField(choices=[(1, 'Text'), (2, 'Number'), (3, 'Single selection'), (4, 'Multi selection'), (5, 'Currency')], default=(1, 'Text'), max_length=128),
        ),
    ]
