# Generated by Django 3.1.3 on 2020-11-23 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_auto_20201123_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='address',
            field=models.CharField(default=None, help_text='This field should be set if beneficiary is legal client', max_length=1024, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='legal_client_title',
            field=models.CharField(default=None, help_text='This field should be set if beneficiary is legal client', max_length=128, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='phone',
            field=models.CharField(default=None, help_text='This field should be set if beneficiary is legal client', max_length=14, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.human'),
        ),
    ]
