# Generated by Django 3.0 on 2020-11-03 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_auto_20201103_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledger',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='pledger',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.Bank'),
        ),
    ]
