# Generated by Django 3.1.3 on 2020-11-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_auto_20201123_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='fields',
            field=models.ManyToManyField(blank=True, to='insurance.ProductField'),
        ),
    ]
