# Generated by Django 3.1.3 on 2020-11-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_auto_20201122_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='fields',
            field=models.ManyToManyField(blank=True, null=True, to='insurance.ProductField'),
        ),
    ]
