# Generated by Django 3.0 on 2020-11-03 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance', '0006_auto_20201103_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policytransfers',
            name='act_date',
        ),
        migrations.RemoveField(
            model_name='policytransfers',
            name='act_number',
        ),
        migrations.RemoveField(
            model_name='policytransfers',
            name='document',
        ),
        migrations.RemoveField(
            model_name='policytransfers',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='policytransfers',
            name='policy_number_from',
        ),
        migrations.RemoveField(
            model_name='policytransfers',
            name='policy_number_to',
        ),
        migrations.AddField(
            model_name='policytransfers',
            name='policies',
            field=models.ManyToManyField(to='insurance.Policy'),
        ),
        migrations.AddField(
            model_name='policytransfers',
            name='to_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
