# Generated by Django 3.1.3 on 2020-11-18 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_profile_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='Тип офис')),
                ('description', models.CharField(max_length=2048, verbose_name='Тип офис')),
            ],
        ),
        migrations.AddField(
            model_name='insuranceoffice',
            name='founded_date',
            field=models.DateField(null=True, verbose_name='Основан'),
        ),
        migrations.AddField(
            model_name='insuranceoffice',
            name='location',
            field=models.CharField(default='', max_length=1024, verbose_name='Местонахождение'),
        ),
        migrations.AddField(
            model_name='insuranceoffice',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.region'),
        ),
        migrations.AddField(
            model_name='insuranceoffice',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.officetype'),
        ),
    ]
