# Generated by Django 2.2.6 on 2020-11-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_auto_20201103_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='person',
        ),
        migrations.AddField(
            model_name='bank',
            name='address',
            field=models.CharField(default=None, max_length=1024, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='bank',
            name='inn',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='mfo',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='name',
            field=models.CharField(default=None, max_length=128, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='bank',
            name='phone_number',
            field=models.CharField(default=None, max_length=14, verbose_name='Номер телефона'),
        ),
    ]
