# Generated by Django 3.1.3 on 2020-11-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_auto_20201118_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceoffice',
            name='parent_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
