# Generated by Django 3.1.3 on 2020-11-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0010_auto_20201119_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='series',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
