# Generated by Django 3.1.3 on 2020-11-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0011_region_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.RenameModel(
            old_name='Region',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='is_exist',
            new_name='is_active',
        ),
    ]
