# Generated by Django 3.1.3 on 2020-11-19 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0012_auto_20201119_0607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='District',
        ),
    ]
