# Generated by Django 3.1.3 on 2020-11-19 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0014_location_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceoffice',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='insuranceoffice',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.insuranceoffice'),
        ),
    ]
