# Generated by Django 3.1.3 on 2020-11-19 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0017_clientrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insuranceoffice',
            old_name='type',
            new_name='office_type',
        ),
        migrations.AlterField(
            model_name='insuranceoffice',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.insuranceoffice'),
        ),
    ]
