# Generated by Django 3.1.3 on 2020-11-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0018_auto_20201119_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, verbose_name='Класс')),
                ('name', models.CharField(max_length=255, verbose_name='Продукт')),
                ('description', models.CharField(max_length=6000, verbose_name='Описание')),
                ('is_exist', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='group',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='klass',
        ),
        migrations.AddField(
            model_name='producttype',
            name='code',
            field=models.CharField(max_length=15, null=True, verbose_name='Код'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='ProductTypeClass',
        ),
        migrations.AddField(
            model_name='producttype',
            name='classes',
            field=models.ManyToManyField(max_length=3, null=True, to='insurance.ProductTypeCode'),
        ),
    ]
