# Generated by Django 3.1.3 on 2020-11-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0019_auto_20201120_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='branchName',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Наименования филиала'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='checking_account',
            field=models.CharField(default=None, max_length=30, null=True, verbose_name='Расчётный счёт'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='mfo',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(default=None, max_length=128, verbose_name='Наименования банка'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='phone_number',
            field=models.CharField(default=None, max_length=14, null=True, verbose_name='Номер телефона'),
        ),
    ]
