# Generated by Django 3.1.3 on 2020-11-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0021_contract'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
