# Generated by Django 3.1.3 on 2020-11-20 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0022_delete_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceoffice',
            name='bank',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.bank'),
        ),
        migrations.AddField(
            model_name='insuranceoffice',
            name='contact',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Contact'),
        ),
    ]
